### ISSUE TITLE
PIA port assignment API is not responding

### ISSUE THREAD

**Issue by werkshy** [binhex/arch-int-openvpn#11]
My arch-delugevpn container is failing to come up because the call to an IP address athttps://github.com/binhex/arch-int-openvpn/blob/master/run/root/getvpnport.sh#L78-L81 is failing.

Setting `STRICT_PORT_FORWARD=no` is a workaround.

**Comment by binhex** [comment]
see Q10 and Q11:-
https://github.com/binhex/documentation/blob/master/docker/faq/vpn.md
