### ISSUE TITLE
List of VPN remotes not supported

### ISSUE THREAD

**Issue by mtalexan** [binhex/arch-int-openvpn#12]
Related to https://github.com/binhex/arch-qbittorrentvpn/issues/41

A method of providing a list of VPN remotes that have their own protocol and port is not available.  This would be required to allow resolution of the linked issue.

**Comment by mtalexan** [comment]
Currently the variables `VPN_REMOTE`, `VPN_PROTOCOL`, and `VPN_PORT` are single-entry variables provided by the derived container.

I would propose that these be converted to `VPN_REMOTE_LIST`, `VPN_PROTOCOL_LIST`, and `VPN_PORT_LIST` arrays.  
For backwards compatibility, these should be checked first and used if present, but then the single-entry variables used if the arrays aren't set.

**Comment by mtalexan** [comment]
As part of the changes, leaving the ovpn file mostly intact seems like a better choice for maintainability.  Commenting out lines rather than removing them, and adding new lines while commenting out the old ones would be preferable.

**Comment by binhex** [comment]
multi remote line support is now in, see here Q20:- https://github.com/binhex/documentation/blob/master/docker/faq/vpn.md
